# Generated by Django 2.2.2 on 2019-06-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='voting',
            name='result',
            field=models.IntegerField(),
        ),
    ]
