# Generated by Django 2.2.2 on 2019-06-15 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0002_auto_20190615_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='links',
        ),
        migrations.AddField(
            model_name='voting',
            name='links',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='related_maps', to='voteapp.Menu'),
        ),
    ]
