# Generated by Django 2.2.2 on 2019-06-16 08:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voteapp', '0003_auto_20190615_1943'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='links',
        ),
        migrations.AddField(
            model_name='voting',
            name='likes',
            field=models.ManyToManyField(blank=True, default='', related_name='related_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voting',
            name='links_to_menu',
            field=models.ManyToManyField(blank=True, default='', related_name='related_links', to='voteapp.Menu'),
        ),
    ]
