# Generated by Django 2.2.2 on 2019-06-16 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0004_auto_20190616_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='links_to_menu',
        ),
        migrations.AddField(
            model_name='voting',
            name='links_to_menu',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='related_links', to='voteapp.Menu'),
        ),
    ]
